name: Build and Publish Images

on:
  push:
    tags: [ 'ruby-*.*.*' ]

jobs:
  build:
    name: Build Images

    strategy:
      fail-fast: false
      matrix:
        RUBY_VERSION:
          - 3.3.0
          - 3.2.3
          - 3.2.2
          - 3.2.1
          - 3.2.0
          - 3.1.4
          - 3.1.3
          - 3.1.2
          - 3.1.1
          - 3.1.0
          - 3.0.6
          - 3.0.5
          - 3.0.4
          - 3.0.3
          - 3.0.2
          - 3.0.1
          - 3.0.0

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set Image version env variable
        run: echo "IMAGE_VERSION=$(echo ${{ github.ref_name }} | tr -d ruby-)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build Dev Container Image
        uses: devcontainers/ci@v0.3
        env:
          RUBY_VERSION: ${{ matrix.RUBY_VERSION }}
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/rails/devcontainer/images/ruby
          imageTag: ${{ env.IMAGE_VERSION }}-${{ matrix.RUBY_VERSION }},${{ matrix.RUBY_VERSION }}
          subFolder: images/ruby
          push: always
          platform: linux/amd64,linux/arm64