name: Build and Publish Images

on:
  push:
    tags: [ 'ruby-*.*.*' ]

jobs:
  build:
    name: Build Images

    strategy:
      fail-fast: false
      matrix:
        RUBY_VERSION:
          - 3.3.1
          - 3.3.0
          - 3.2.4
          - 3.2.3
          - 3.2.2
          - 3.2.1
          - 3.2.0
          - 3.1.5
          - 3.1.4
          - 3.1.3
          - 3.1.2
          - 3.1.1
          - 3.1.0
          - 3.0.7
          - 3.0.6
          - 3.0.5
          - 3.0.4
          - 3.0.3
          - 3.0.2
          - 3.0.1
          - 3.0.0

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and Publish Image
        uses: ./.github/actions/build-and-publish-image
        with:
          ruby_version: ${{ matrix.RUBY_VERSION }}
          image_tag:  ${{ github.ref_name }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: ${{ github.repository_owner }}